"""Dynamical systems — the long-term behaviour of things that evolve.

Where :mod:`maths_coding.number_theory.dynamics` studies iteration over *finite* arithmetic
worlds, this package treats the *continuous* and *real* dynamical systems of analysis: flows
generated by differential equations and the iteration of maps on the real line. The unifying
question is qualitative rather than quantitative — *not* "where is the trajectory at time
``t``?" but "where does it end up, and is that destination stable?"

The method throughout is **linearization**: near an equilibrium, a nonlinear system looks
like its Jacobian, and the eigenvalues of that Jacobian decide the local fate (the
Hartman–Grobman theorem makes this rigorous at hyperbolic points). This is the same
"operator + eigenstructure" refrain that runs through the rest of ``maths_coding``, now in
the setting of stability theory.

Modules
-------
continuous
    Autonomous ODE systems ``ẋ = F(x)``: finding equilibria, the Jacobian, and classifying
    them (stable/unstable node, saddle, spiral, centre) from eigenvalues.
discrete
    Iterated maps ``x_{n+1} = f(x_n)``: fixed points and their multipliers, the logistic
    map, and the **Lyapunov exponent** that quantifies sensitive dependence — the
    fingerprint of chaos.
bifurcations
    How the qualitative picture *changes* as a parameter varies: the saddle-node,
    transcritical, and pitchfork normal forms, and the period-doubling road to chaos in the
    logistic map (a demonstration script with plots).

Perturbation theory (:mod:`maths_coding.perturbation_theory`) is the natural companion —
it asks how these systems respond to small changes.
"""
