"""Root systems, Cartan matrices, and Weyl groups — the combinatorial skeleton of Lie theory.

A semisimple Lie algebra (the global object behind :mod:`maths_coding.algebra.lie_algebra`) is
controlled by a finite, highly rigid configuration of vectors: its **root system** ``Φ``. The
roots are the nonzero weights of the adjoint action; a choice of **simple roots**
``α₁, …, αₗ`` is a basis from which every root is a non-negative or non-positive integer
combination. All the structure is packed into the **Cartan matrix**

    a_{ij} = 2 ⟨αᵢ, αⱼ⟩ / ⟨αⱼ, αⱼ⟩   ∈ ℤ,

with ``2`` on the diagonal and non-positive integers off it — the integrality is the
crystallographic condition that makes only finitely many root systems possible (the
``A``–``B``–``C``–``D`` families plus the exceptionals ``G₂, F₄, E₆, E₇, E₈``).

Each root ``α`` gives a **reflection** ``s_α(v) = v − 2⟨v,α⟩/⟨α,α⟩ · α`` of the ambient space,
and the group they generate is the **Weyl group** ``W`` — a finite reflection group that
permutes the roots. Generating ``Φ`` is just taking the ``W``-orbit of the simple roots, and
``|W|`` is the size of the symmetry group they generate. The headline numbers come out exactly:
``A₂`` has 6 roots and ``|W| = 6 = |S₃|``; ``B₂`` has 8 roots and ``|W| = 8``; ``G₂`` has 12
roots and ``|W| = 12``; ``Aₙ`` has ``|W| = (n+1)!`` (the Weyl group is ``S_{n+1}``).

Pure-Python and exact (vectors of :class:`fractions.Fraction`), so it runs without SageMath:

- :func:`cartan_matrix` — the integer matrix ``a_{ij}`` from a set of simple roots.
- :func:`reflection` — the reflection ``s_α``.
- :func:`generate_roots` — the full root system as the Weyl orbit of the simple roots.
- :func:`weyl_group_order` — ``|W|`` (the reflection group as permutations of the roots).
- :data:`SIMPLE_ROOTS` — builders for ``Aₙ, Bₙ, Cₙ, Dₙ`` and ``G₂``.
"""

from fractions import Fraction


def _dot(u, v):
    return sum(a * b for a, b in zip(u, v))


def _vec(coords):
    return tuple(Fraction(c) for c in coords)


def cartan_matrix(simple_roots):
    """
    The Cartan matrix ``a_{ij} = 2⟨αᵢ,αⱼ⟩/⟨αⱼ,αⱼ⟩`` of a list of simple roots.

    Returns a list of rows of integers (``2`` on the diagonal, non-positive off-diagonal).
    """
    rows = []
    for ai in simple_roots:
        row = []
        for aj in simple_roots:
            val = 2 * _dot(ai, aj) / _dot(aj, aj)
            row.append(int(val))
        rows.append(row)
    return rows


def reflection(v, alpha):
    """The reflection ``s_α(v) = v − 2⟨v,α⟩/⟨α,α⟩ · α`` (an exact rational vector)."""
    c = 2 * _dot(v, alpha) / _dot(alpha, alpha)
    return tuple(vi - c * ai for vi, ai in zip(v, alpha))


def generate_roots(simple_roots):
    """
    The full root system: the Weyl-group orbit of the simple roots under all simple reflections.

    Returns a sorted list of roots (tuples of :class:`fractions.Fraction`).
    """
    roots = set(tuple(r) for r in simple_roots)
    frontier = list(roots)
    while frontier:
        new = []
        for v in frontier:
            for alpha in simple_roots:
                w = reflection(v, tuple(alpha))
                if w not in roots:
                    roots.add(w)
                    new.append(w)
        frontier = new
    return sorted(roots)


def _root_permutation(simple_roots, alpha, roots, index):
    """The permutation of the root set induced by the reflection ``s_α`` (as an index tuple)."""
    return tuple(index[reflection(r, tuple(alpha))] for r in roots)


def weyl_group_order(simple_roots):
    """
    The order ``|W|`` of the Weyl group, realized as the permutation group of the root system
    generated by the simple reflections.
    """
    roots = generate_roots(simple_roots)
    index = {r: i for i, r in enumerate(roots)}
    gens = [_root_permutation(simple_roots, a, roots, index) for a in simple_roots]
    identity = tuple(range(len(roots)))

    group = {identity}
    frontier = [identity]
    while frontier:
        nxt = []
        for g in frontier:
            for s in gens:
                comp = tuple(s[g[i]] for i in range(len(roots)))   # apply g then s
                if comp not in group:
                    group.add(comp)
                    nxt.append(comp)
        frontier = nxt
    return len(group)


# Standard simple-root realizations (in Euclidean space) for the classical families + G2.
def _A(n):
    return [_vec([1 if j == i else (-1 if j == i + 1 else 0) for j in range(n + 1)]) for i in range(n)]


def _B(n):
    roots = [_vec([1 if j == i else (-1 if j == i + 1 else 0) for j in range(n)]) for i in range(n - 1)]
    roots.append(_vec([1 if j == n - 1 else 0 for j in range(n)]))          # short root e_n
    return roots


def _C(n):
    roots = [_vec([1 if j == i else (-1 if j == i + 1 else 0) for j in range(n)]) for i in range(n - 1)]
    roots.append(_vec([2 if j == n - 1 else 0 for j in range(n)]))          # long root 2 e_n
    return roots


def _D(n):
    roots = [_vec([1 if j == i else (-1 if j == i + 1 else 0) for j in range(n)]) for i in range(n - 1)]
    roots.append(_vec([1 if j in (n - 2, n - 1) else 0 for j in range(n)]))  # e_{n-1}+e_n
    return roots


SIMPLE_ROOTS = {
    "A": _A,
    "B": _B,
    "C": _C,
    "D": _D,
    "G2": lambda: [_vec([1, -1, 0]), _vec([-2, 1, 1])],
}


if __name__ == "__main__":
    print("=" * 70)
    print("Root systems, Cartan matrices, and Weyl groups")
    print("=" * 70)

    cases = [
        ("A1", _A(1)), ("A2", _A(2)), ("A3", _A(3)),
        ("B2", _B(2)), ("C2", _C(2)), ("D3", _D(3)),
        ("G2", SIMPLE_ROOTS["G2"]()),
    ]
    # Known data: #roots and |W| (Weyl group order).
    expected = {
        "A1": (2, 2), "A2": (6, 6), "A3": (12, 24),
        "B2": (8, 8), "C2": (8, 8), "D3": (12, 24),
        "G2": (12, 12),
    }

    print(f"\n{'type':<5}{'Cartan matrix':<22}{'#roots':<9}{'|W|':<7}{'matches known'}")
    for name, sr in cases:
        C = cartan_matrix(sr)
        nroots = len(generate_roots(sr))
        w = weyl_group_order(sr)
        exp_r, exp_w = expected[name]
        flat = ";".join(",".join(str(x) for x in row) for row in C)
        ok = (nroots, w) == (exp_r, exp_w)
        print(f"{name:<5}[{flat:<19}]{nroots:<9}{w:<7}{ok}")

    print("\n  (Cartan integrality is the crystallographic restriction; A_n has |W| = (n+1)! = |S_{n+1}|,")
    print("   B2/C2 share |W| = 8, and G2 is the exceptional rank-2 system with 12 roots and |W| = 12.)")
