"""Divergences between distributions — and how the Fisher metric hides inside them.

A *divergence* measures how far apart two distributions are. Unlike a distance it need not
be symmetric and need not satisfy a triangle inequality, but it is non-negative and zero
only when the two distributions coincide. The central example is the **Kullback–Leibler
divergence**

    KL(p ‖ q) = E_p[ log(p/q) ] = ∫ p log(p/q) dx   (or Σ in the discrete case).

Two structural facts connect KL to the geometry of
:mod:`maths_coding.geometry.information_geometry.fisher_metric`:

1. **Infinitesimally, KL *is* the Fisher metric.** Expanding to second order in a small
   parameter step,

       KL(p_θ ‖ p_{θ+dθ}) = ½ dθᵀ g(θ) dθ + O(|dθ|³),

   so the Fisher matrix ``g`` is the Hessian of KL on the diagonal — the unique Riemannian
   metric KL induces. (:func:`fisher_from_kl`)

2. **For exponential families, KL is a Bregman divergence.** With log-partition ``ψ`` and
   natural parameters,

       KL(p_{θ₁} ‖ p_{θ₂}) = B_ψ(θ₂ ‖ θ₁),

   the Bregman divergence generated by the convex function ``ψ``. (:func:`bregman_divergence`)

These are the two halves of the "dually flat" structure at the heart of information
geometry.
"""

from sage.all import *


def kl_divergence(p, q, x, lo, hi):
    """
    Kullback–Leibler divergence ``KL(p ‖ q) = ∫ p log(p/q) dx`` for continuous densities.

    Parameters
    ----------
    p, q : symbolic expressions
        Densities in the variable ``x``.
    x : sage variable
    lo, hi : symbolic
        Integration limits (e.g. ``-oo, oo``).

    Returns
    -------
    Symbolic value of the divergence (relies on Sage evaluating the integral).
    """
    return integrate(p * log(p / q), x, lo, hi).simplify_full()


def kl_divergence_discrete(p, q):
    """
    KL divergence ``Σ pᵢ log(pᵢ/qᵢ)`` between two finite probability vectors.

    Parameters
    ----------
    p, q : sequences of symbolic or numeric probabilities (same length, each summing to 1).

    Returns
    -------
    Symbolic value of the divergence.
    """
    if len(p) != len(q):
        raise ValueError("p and q must have the same length")
    return sum(pi * log(pi / qi) for pi, qi in zip(p, q))


def bregman_divergence(F, thetas, point_p, point_q):
    """
    Bregman divergence ``B_F(p ‖ q) = F(p) - F(q) - ∇F(q)·(p - q)`` of a convex generator ``F``.

    Geometrically: the gap at ``p`` between ``F`` and its tangent plane at ``q``. Taking
    ``F = ψ`` (the log-partition of an exponential family) recovers the KL divergence:
    ``KL(p_{θ₁} ‖ p_{θ₂}) = B_ψ(θ₂ ‖ θ₁)``.

    Parameters
    ----------
    F : symbolic expression
        Convex function of the variables ``thetas``.
    thetas : list of sage variables
    point_p, point_q : dict
        Substitutions ``{theta_k: value}`` giving the two points.

    Returns
    -------
    Symbolic value of ``B_F(p ‖ q)``.
    """
    Fp = F.subs(point_p)
    Fq = F.subs(point_q)
    grad_at_q = [diff(F, th).subs(point_q) for th in thetas]
    inner = sum(grad_at_q[k] * (point_p[thetas[k]] - point_q[thetas[k]])
                for k in range(len(thetas)))
    return (Fp - Fq - inner).simplify_full()


def fisher_from_kl(log_pdf, params, x, lo, hi):
    """
    Recover the Fisher metric as the Hessian of KL along the diagonal.

    Forms a second copy ``θ'`` of the parameters, computes ``KL(p_θ ‖ p_{θ'})``, and takes
    ``∂²/∂θ'ᵢ ∂θ'ⱼ`` evaluated at ``θ' = θ``. The result equals the Fisher information
    matrix — a direct check of fact (1) in the module docstring.

    Parameters
    ----------
    log_pdf : symbolic expression in ``x`` and ``params``
    params : list of sage variables
    x : sage variable
    lo, hi : symbolic integration limits

    Returns
    -------
    sage matrix
        The Hessian of KL at coincidence, i.e. the Fisher metric ``g(θ)``.

    Notes
    -----
    Integration-heavy; intended as a conceptual cross-check of
    :func:`maths_coding.geometry.information_geometry.fisher_metric.fisher_metric_expected`.
    """
    n = len(params)
    primed = [SR.var(f"{params[i]}_prime") for i in range(n)]

    p_theta = exp(log_pdf)
    log_pdf_primed = log_pdf.subs({params[i]: primed[i] for i in range(n)})
    p_primed = exp(log_pdf_primed)

    KL = integrate(p_theta * log(p_theta / p_primed), x, lo, hi)

    g = matrix(SR, n, n)
    at_theta = {primed[i]: params[i] for i in range(n)}
    for i in range(n):
        for j in range(n):
            g[i, j] = diff(KL, primed[i], primed[j]).subs(at_theta).simplify_full()
    return g


if __name__ == "__main__":
    # 1. KL between two Gaussians with common sigma, and its Hessian -> Fisher = 1/sigma^2.
    var('x mu sigma mu2')
    assume(sigma > 0)
    p = 1 / (sigma * sqrt(2 * pi)) * exp(-(x - mu) ** 2 / (2 * sigma ** 2))
    q = 1 / (sigma * sqrt(2 * pi)) * exp(-(x - mu2) ** 2 / (2 * sigma ** 2))
    KL = kl_divergence(p, q, x, -oo, oo)
    print("KL(N(mu) || N(mu2)) =", KL, "   (expected (mu - mu2)^2 / (2 sigma^2))")
    fisher = diff(KL, mu2, 2).subs({mu2: mu}).simplify_full()
    print("d^2/dmu2^2 KL at mu2=mu =", fisher, "   (= Fisher 1/sigma^2)")

    # 2. Exponential-family identity: KL = Bregman divergence of the log-partition (Bernoulli).
    var('theta')
    psi = log(1 + exp(theta))                       # Bernoulli log-partition
    p1, p2 = QQ(3) / 10, QQ(4) / 10                 # two Bernoulli means (not symmetric)
    t1, t2 = log(p1 / (1 - p1)), log(p2 / (1 - p2))
    kl_direct = kl_divergence_discrete([p1, 1 - p1], [p2, 1 - p2])
    breg = bregman_divergence(psi, [theta], {theta: t2}, {theta: t1})
    print("\nBernoulli KL(p1||p2) direct =", kl_direct.n())
    print("Bregman B_psi(theta2||theta1) =", breg.n(), "   (should match)")
